title: OpenState
description: Building a collective memory about how public services behave
url: https://openstate.andreclemente.dev
theme: jekyll-theme-primer

collections:
  observations:
    output: false
    sort_by: date
