remote_theme: just-the-docs/just-the-docs

title: OpenState
description: Um sistema de observabilidade estruturado para serviços públicos
url: https://openstate.andreclemente.dev

color_scheme: dark

search_enabled: false

aux_links:
  "EN": "/en/"

nav_sort: case_insensitive

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
